language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: hnRHuR86f0o/qdYDvRJ3gzChCPWNU3lp9J1sBofF6VQ5Fp6duAasWLujwV65OB7WAMN5OMcpbJ0OIJBK86v+veH81GOa0eFJL/ED2nHX1mnsV5uwfrpfspyEZrTxMDk5xDglmnhsYQGbt4KKQwp3D6HfpwnbZ+niOnpKhuGEuwUi5BGA+ki8BDEUKn778seZrzA0lvXhKBKUMQTaD6+JmRdwUQ2y6519N0OcY1GIW9T7DE0a9aeMiCMTlQecsMOb7y28oe2p/ZrblB2MKf+xaIDloxNiG7/1iqNI8YXWlcnBHJccwmqifZlx6U5RCP24kIIm3/2wQ0dDtk4SnQl+SEiZ0U6vVogJuHmAHzuzNz42ckkr+t2nIjpBSALhidVq3qF06aqbGO5KPePZFfdUwAEwH3JsjMhRdmSwzcZpLikrinIN3Dg70umc4esHcJK0HBW1tLWm3zKjJ2aAFYTlPhZ2+v32q82ZeWs1NTv5kXg3neLV+qLsoYJwvidNU4R1qcwBRs9SZqMIObfKkMtxZgM6+PcxBZ2Use6qsIvlTJiI7h9ZWevNdBVrPGZgH1O3bLtIRLaAlxlDgKeuvQ6AfP9E0Dq1Ps9E04g3kJ56v3AKmrHaKDTbJtHazhDYkqfLQzi9fpZHO3/6H3KxykeT1wYzHvKJhVvTQjWKwAWodFk=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
