language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: fbrundu
  password:
    secure: jKKlD1JHk0A7Xw6YOq3tyt6mq3zzCInTwlzRwS8PO2IBe4ECnRmGivPbRVJWQVN9waJWHpCMCQFpD5Rg2ySo3UV+ao47FQvdjbMJORr90XudQ7M1gnzWM+eC5DLnuKC8M2mMpMNEaE22W5j8Q1qGTNqGGssO3ruau7wm0ecI/BUnmzY1UCdzRAlvidKwOpSQpMrejdyhsHAA4huz/6GTaLv1b+hhEMZ9L6FPXFCHmnsAwOgaTxEGP2doOaYEgk1OD5Y8ZFD7XoMo73BejeDCfM46aJHHrLU2HK2MvNDd6/RPkPGud0wb0uqqs0a7XtL02JLrehT+EdoNevqn/LC2PpVrUUOB9UGhQc/F8MyYEyuW5NORXWb/YwDPdXL1V/Gqak/MwZP8eILz0q7qTJJ+NjIL5JBwTeEsFNhucItRWcRT7QMjZ4xkkrEZ7FVqJ1cvDbZEOXxNu7QA8GrWKZKrT2KCkxKjWegtFXC5zUFojja1H82Fip1qJ3Gng29waHuBIPp8iJxSZEy7vj9HSJJNz47fGyFuD+N3rFxO78WsCS6mJXEbATn082v99Cvj/QCdlD3wTgG5IZW4yx+48uk2kcjVtZcBCNSyE2bZWW4Gq377JuDn9ditTZEZ2ZsQOrTg7YiTLc7HWJdUnB1afKQI/hHw3ohlMBrdVkPDYhSgKKM=
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
  skip_cleanup: true
  skip_existing: true
