language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: qV3TlGpgEa+M7juKrCHZnXXbXML0RS/1Z3d6i7N9shgk0IWHp/A3QvJ4dmfyu3DqdneOu+x+EaQVKqwL7C/kqro1XQjlhv0NgWYCR0mCTaxcCuZhELsWR0nXSt7stGbNXFHod1Fep/PPlqqvPOuJwLYa2VFM3y+eAmB5bUNG3owsGGpZJk5IAJVJuDKk4moZRY7xwu9lYmI7VSIHMZBuutczevvUkXh9gbmIkMZkJmtLkus+cD3ilX8t7CXqd6OP2sYrgeqgoE3YKGEbB3ZY+vom9KpUrrXydSYvP9XUejyTviyh8ZIgg0Hi9kCqyWXiy+hlnWwg1UiNnQbTphkMdcRKqPXON98i9iszSXapvtEli0hf6NeEgVHqLseIz46QGyMkXV7qxB/yY9ljQaWImldADC3B4H2pBHNbdZixGcSptEUe2BK1Fi9/dKLqPwCiVjO731xzoSM/jMQBkICElSrMvULAR3efbDAJiinMC8+Bt7n1MsmORg3Ds7u65B+6gFYbgzTWfi4pDuBnjlhWt1qL0MfKSgJ/p+g5B/ATtvxtzgiR3dHwfMl2F/LszvsaqTFYHMJ30qVIJvL/9MOMaYPDjjEl2haI4Kl+CxXoTBtCSXIzUHhQ4Wt47a7JP2FuA3P/iGsg5qMFaDQAexp7KTWgMEJi0ZyskDd2K7k12bc=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
