language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: iU8Y7mVu/+9Fp+Ghow/9ccvGNwkdW7FSHbXlfTaohAIQ8MRheVeZSAINoBZc6yDNHnMNPDlUyNzrRPLnhPHSkv1suoGImziF03dOvZHwfHPr5CdRi+iStc4PIhrPYmrTp81B3AurgAXpQLKDDaWzUPP8l74L7AIQ80zhRcT+zrtZjqIJ1lsJMPwD3WagR3P7+XJVqGEriOtfb+H8HFziUCMKy1AFLKM43VH5E5XjFL2ghL6Xx2G4nOulwVS2p25U0EUNjUOWa2C/mWnLWasEB9OUOmNIjMMltbJ880Yu7QhpWQyvX1BrecLimT+RaDrnwDuw8hc0MdS/c62Rd/h3Um3vMX+G0ggfRce2E+DvQ3BTqVIybYqIgyP7KpL6QL+s6qZxbQthXqJ5ZkcZV1Q83OlcUJrtDYP+djQWeCRV7DBJp9siZy/iYX7xini6ETPabpFtF1LQvTPGS/PDWSGVZCNz1QNS1QTDnN5awkdoVolThcZr3Bb86+pu96+ofiz14OsvE6eX9POuk9uKOu4F7YZ5zcH/L+77MEUvWuYqYH0LDswQSkPRowl1EAzrqZSBsF+/AM+4z53ZksamEhZJOkY8SD+Rdjt4f9klIwdSYUNNSRJ7TrELRjfPny/wQnDdA/GpWHBZb3h5vMoTB1H0w3IRYpEjn5165ibQC9jJSJo=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
