language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: s8f56cu1LQsObrrs8MSoCCc8aOCBG8HZuPD9hiptdevi8S8MhsvsmomkWuZ6lVEVfjzT7NsLfD14ucWfllf5PCQ9PuVl7uXzKRHmEI3w4RdLibI4tNi1q5qHJHcvNZJSnI7ocSGmVUFK+FHVSgqOX1Z57lx9AbcNvAevPc+I2eXDGsofTztsj+8s8N7yTVAbUyHKHpAyGTmvBRxSR4jzQAry/hoR5+ukBoFgelTiyJgOFw6Yt5aC6uReAkrMP+NLAnGCokuBGPVK6bzdD2vQRrWvvI0a+pNbEBQBsl4hYuYmozTbAxsYuDTiLadEIdMNE+AEwSMqREvKX5yvrJVwpQD6Vfs5N4amPktNjEkXcu0swbTzz1nM4QKGyPGd2um6g7OhwCP+qrMiECDwT9evrQmp67QbaEbobnyFBkWLK4bGNjtpJ0V3/YjklTRqh2gY+3mcb3tN7dSSPh/nqN8XvDDa9wXsfdhYTN6PDlA6nb9aVBq/7VeYvdwe133t742xeMpMa4Rq/titL/dv2XVMqPc8sPoGgHX04qPbjkGfTjlWNtj4XdhG9AQKgV4tuxpzUDSCXU8lMQzEGlSeH3/I0vbX3EAcZiDdPSIGeF9IIO/gyhXqfY8SF8DP1smSJ9+T+z8vSAfBaNR6fXIG40+5x1BVNg1lnVnc2UMRtMVJc/Q=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
