language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: MMOObuz72KHdgggH0qLND+a+6T+hs9OyEpVsgeymf1UJQqYkH1L9b9s1z/id8m/2eBD4JubAUMj8Ky9EbNxfhxaYMbMvaPYwyYdT+gu/oITBUIasISXwjeDQWsWt4jpiK8MmMrF0YZPLMTss7DxWPoEzeauMHFiI9ZD262A6EPLsL1SPRPoZyBxaVbBpCBy8x63TvrHuUwmd15ljMguftkpyW0ZEC1A0O4XYqnTRIs3YWErj/ZtknpOpsJqUpD8pNW88RyeMdrUoEraC3jtT+TifDGuSkau0v/wVdaE5fbwHdpMWAS+KmFxbJZslrim2V08zwNYZlTf9Ag7a+ZDmGaRN9l+p2Y7XWMwvGgpJAVoW6wijEILeNo1iROCVCMvuUC75z/KK7movtYIQA8OWmxku6f2D3XbnYDnOxXE87TNty/QMvEHuDVXHQrM/1SGJcpuPIp4u1ruYeAo6XPB/q/HTj5segxPjvCdPxWwYRWIJ5DM+BvxvdUEJtCbraUIDXWNkDBpxyfhyaRrXJjumEfMU4IuLHnPXidEY0RreWV2ZgdTtPKqBlNQ2GsFOk6U6MnMziyRwBhfkgNqv2kYXvCgjyJ7y/lNjNTkS26p9MHlQNCd0rfnw7sBb7sXCKrTnAzL06E+FqBeq/QeTVHmcW8AxVp+pW0KPiCNpXZV80iM=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
