language: python

branches:
  only:
  - master

jobs:
  include:
    - name: Linux | x86_64 + i686 | Python 3.6
      language: python
      python: 3.6
      services: docker
      env:
      - PYTHON=python
      - TOXENV=py

    - name: Linux | arm64 | Python 3.6
      language: python
      python: 3.6
      services: docker
      arch: arm64
      env:
      - PYTHON=python
      - TOXENV=py

    - name: Linux | ppc64le | Python 3.6
      language: python
      python: 3.6
      services: docker
      arch: ppc64le
      env:
      - PYTHON=python
      - TOXENV=py

    # - name: macOS | x86_64 | Python 3.x
    #   os: osx
    #   env:
    #     - PYTHON=python3
    #     - PYTEST_ADDOPTS='-k "unit_test or test_0_basic" --suppress-no-test-exit-code'

    # - name: Windows | x86_64 | Python 3.6
    #   os: windows
    #   language: shell
    #   before_install:
    #    - choco install python3 --version 3.6.8 --no-progress -y
    #    # Update root certificates to fix SSL error; see http://www.chawn.com/RootCerts.htm
    #    - powershell "md C:\temp\certs; CertUtil -generateSSTFromWU C:\temp\certs\RootStore.sst; Get-ChildItem -Path C:\\temp\certs\Rootstore.sst | Import-Certificate -CertStoreLocation Cert:\\LocalMachine\\Root\\ | out-null"
    #   env:
    #     - PYTHON=C:\\Python36\\python

install:
- $PYTHON -m pip install -U tox-travis
- $PYTHON pip install -r requirements_dev.txt
- $PYTHON -m pip install cibuildwheel==1.8.0

script: tox -e ${TOXENV}

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: Cg6gBwNFeLQeIjCwdhhvEMf37m+0LrGRyunrjqqwgla7Co5ImgHzg4gVzeT/R18j9K2I2Tf12gPhFt7ZF1nfoBjwGJ7eciB+4O5YK2sP/1C3hGpuyl6twRajTa6RA6IfHJ4S7FZA7TbyZ4Y7BQjd9tf8wTC3DFqu2woYwbWw3uGzJ9AJHkbT8bj8lBVBA4ETzu5Y7EuwGbXLwVi5Hx87DezNAh9iV5imYco7w3lOPY+3S33wS262zVNVpeMuFTEOyPwMWv2oTqmsQL1yRYxEyAUdJKSPcTtLPxP0WRWxwvtOsH9lhn5vz+j8c6fMXOd9Oub0wwp6W1MEEZcIN+/wx2uDpYFaoEe04Zq9TDIMbxGIjqvK3rGrWunbjsUI4I7ldCARtJAp40AAzdWEI4/5ekG1iZDhmSCLHXQs4tyewDf6cUNtyLdr0b2aENQTsA9Y2dEqbrLGQFTcwjdQTkrE+3awDTkwrMfVmLmjRMvb7NIQRn4BLSu9qs/6os/tjpY7fxBak0H+N6LgUgepq34lz499moNB8MtCgcslw08IYE716/+Qzw6DDwlurmbulLUCdESbCaIBFGY9Zx8o3WrOjxb9/xBrjJPbU4MbvXrMN4Xl1Z3CF19tI7y2uCHFhT4zeNOaHmhNLlthXnB3Hzx9o//e64yuPZFxs2apgqMa5aA=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
