language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: fbrundu
  password:
    secure: "QI17s7/pZzeJOZNpVmWnlHwy4sB7pE1qZ2flMWcbzM+iDo3qAfip+b5QngTISxj7K6X+Gby6GEAYjGo6HxwgrR5mkg3IcQ6UzShEo8TFYRmVlUoMRxq3Swee4ch66DlZ0F8sg5dkPfYssl8HXSAJYIIfAfkYVnPImB2oZhO57UnKQgwrG5z/eP/E7dUPtOatnShYnjIWrEExrEGFjoalA+MlBE6VZOLOyxMZdSJsm5GYGmXEiE2C71xOXxZpi5OXuXVT+zef40Kf9rhqp5l2klXbv+r1ynp2Z8+19NRYxyFDSe4us1nEQpOaaPDWkMq/h1YQjfe3hKOSxl4bh6UclBRz0C6eg7SojnC3d+TQauCPV4rqQK+cbfG87i22zKVV4TsE3Chj4LRpqusFQ9Y4bSzpmhIc7tivXs/2L4qPnJhJaaSMR2yFRzkss3+GVnIPuUAoZEwSv4Hjp51s+gBhfw8rxStn/l4mljTFEBHVJC/R14PstSw+IDta+IHfYMI++Ni5im7MbHqOr6Dj6mt77AaQTr0Co7Hcvw4soI3lpYRZxkVmuxL+2YcnUX5ktGOOsEP21MAouDpC8RNVpAkhDQvh3MI2/ruZPuee2eb1eZPHTrmvtJiGpXy29rV14ijYonuDzTVhEIaWG/JzbZCiNgFz6FXrW/34dzchWTPbka4="
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
  skip_cleanup: true
  skip_existing: true
