language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: fbrundu
  password:
    secure: MW7+IWc+waKU4MQiK5pxXEflrAVbVaTmYKz9beQ3b/RDEn/jBal6Xd/hHd5Mex9Ypo7WfA+n15JwxSKBGSsbz687SG1SZKlcBIrgHsNmVzJkoQNjv+y4HTTjBo9e/ib8BiXTTY/4cAWwUI8205wwNhmUAISBtCL23DOkl0lNq6f1E//K9KOcF/oONjq1TDc3YGA/syEqHJ/lNDFlGcoFISVkMiO3hXEOzReqFBANO50D2jMPVweAypCwOViZ5JL5/k8Pgz9rOhXQw2r/0u8YZ9fN7lnrFTVcAVpMC38U4gxtbrG58QdHy3FusBFqufBwZEoyeTOpMTSCNHE5jQbOm8U428EOfapuIABi4+/70fej3wGlpy3fFHXq52AGMKrA5F0ncCyVeVb2SrtqYjIsp7F3uXeYQML7skMxR4fDL6OIGrmOw2H/dpB/yCS/c31UrmH8ZpWw8gGDc5IalodTSVmRbH8oA41wxpgltzSaS4a6QJIcBqfyfycKpJQTpH9JTmamKBWH4/oes0QwCqjh3xnOU/ahej1gSrFTYgJ2CGleKtHtgMsoPO+d1EO0HCzfk/M6QiW9mgs/47wCiyJVgyvM7LNOK10OJ2fHtNrKjyYDIuWM/Z3FvQA3/G7Dzoy5oliHsxQyZug+Dj38PBs/6oan1bXMjcSRlvROez39S70=
  cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
